import org.apache.hadoop.security.protocolPB.RefreshAuthorizationPolicyProtocolServerSideTranslatorPB;
public class FunctionUse11155 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolServerSideTranslatorPB refreshauthorizationpolicyprotocolserversidetranslatorpb = new RefreshAuthorizationPolicyProtocolServerSideTranslatorPB();
}
}